/**
 * @description       : Trigger handler helper class for Account object
 * @author            : Sumant
 * @group             : 
 * @last modified on  : 02-10-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AccountTriggerHelper {
    public void method1() {
        System.debug('AccountTriggerHelper - method1');
    }

    public void method2() {
        System.debug('AccountTriggerHelper - method2');
    }

    public void method3() {
        System.debug('AccountTriggerHelper - method3');
    }
}